---

- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: get user id
      become: false
      shell: |
        set -o pipefail
        id
      register: output
      tags:
        - skip_ansible_lint


    - name: show user id
      debug:
        msg: "{{ output.results }}"

  roles:
    - role: royen99.precheck
