---

- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: get user id
      command: id
      register: output

    - name: show user id
      debug:
        msg: "{{ output.results }}"

  roles:
    - role: royen99.precheck
